swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:8080
tags:
  - name: mutants-controller
    description: Mutants Controller
paths:
  /api/healthCheck:
    get:
      tags:
        - mutants-controller
      summary: Is Alive operation
      description: Return is the microservice is alive with a get operation returning the version
      operationId: healthCheckUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/mutants:
    post:
      tags:
        - mutants-controller
      summary: Is a mutant DNA
      description: Return 200 is a mutant or 403 is a human the DNA received
      operationId: receiveDNAUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: dna
          description: dna
          required: true
          schema:
            $ref: '#/definitions/ModelDNA'
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/stats:
    get:
      tags:
        - mutants-controller
      summary: Stats saved
      description: Return JSON con history data in DB con DNA old verified
      operationId: generalStatsUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  ModelDNA:
    type: object
    properties:
      dna:
        type: array
        items:
          type: string
    title: ModelDNA
