#logger
logging:
  file:
    name: logs.txt
    clean-history-on-start: true
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG

#server
server:
  port: 8080

#database

bd:
  user: "postgres"
  password: "root"
  connectionString: "jdbc:postgresql://localhost:5432/storagedna"

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/storagedna"
    username: "postgres"
    password: "root"
