#logger
logging:
  file:
    name: logs.txt
    clean-history-on-start: true
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG

#server
server:
  port: 8080
  servlet:
    contextPath: /api

#database
spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://35.232.211.162:5432/mutants"
    username: "postgres"
    password: "8mjNDc5cbKfIvL0c"
